---
title: "Figure_1"
author: "Annika Weber"
date: "2022-12-06"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(leaflet)
library(tidyverse)
library(dplyr)
```

```{r}
volcano_data <- read_csv(file = "https://raw.githubusercontent.com/plotly/datasets/master/volcano_db.csv")

indonesia_volcanoes <- volcano_data %>% 
  select(`Volcano Name`, Country, Region, Latitude, Longitude, Elev) %>% 
  filter(Country == "Indonesia")

#created popup info and made bold letters and line break
indonesia_volcanoes <- indonesia_volcanoes %>% 
  mutate(popup_info = paste("<b>Volcano Name:</b>", `Volcano Name`, "<br/>", 
                            "<b>Elevation:</b>", Elev, "Meters"))

volcanoIcon <- makeIcon(iconURL = "https://www.kindpng.com/picc/m/120-1200586_erupting-volcano-volcano-silhouette-png-transparent.png", 
                                           iconWidth = 38, 
                                           iconHeight = 95)

leaflet() %>% 
  addProviderTiles("CartoDB.DarkMatter") %>% 
  addCircleMarkers(data = indonesia_volcanoes, lat = ~ Latitude, 
                   lng = ~ Longitude, radius = 3, 
                   popup = ~popup_info, 
                   color = "red")
             
```

