---
title: "Indonesian Volcanoes"
output: 
  flexdashboard::flex_dashboard:
    theme: 
      version: 4
      bootswatch: sandstone
      base_font: 
        google: Prompt
      heading_font:
        google: Sen
      code_font:
        google: 
          # arguments to sass::font_google() 
          family: JetBrains Mono
          local: false
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(leaflet)
library(tidyverse)
library(dplyr)
library(ggplot2)
library(plotly)
library(forcats)
library(tidyr)
library(ggthemes)
library(ggdark)
library(viridis)
library(leaflet)
library(readr)
library(showtext)

```

Column {data-width=450}
-----------------------------------------------------------------------

### Volcanoes in Indonesia and population size within 5km

```{r}
volcano <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-05-12/volcano.csv')

indonesia_volcanoes1 <- volcano %>% 
  filter(country == "Indonesia") 

#created popup info and made bold letters and line break
indonesia_volcanoes1 <- indonesia_volcanoes1 %>% 
  mutate(popup_info = paste("<b>Volcano Name:</b>", `volcano_name`, "<br/>",
                            "<b>Last Eruption:</b>", last_eruption_year, "<br/>",
                            "<b>Elevation:</b>", elevation, "meters", "<br/>", 
                            "<b>Population size within 5km:</b>", population_within_5_km))
                            
#add population in danger zone information (within 5km)
plot_map <- indonesia_volcanoes1 %>% 
  mutate(transformed_pop = log2(population_within_5_km + 1), 
         pop_color = colorNumeric(c("green", "red"), transformed_pop)(transformed_pop)) %>% 
  leaflet() %>% 
  addProviderTiles("Stamen.Toner") %>% 
  addCircleMarkers(lat = ~ latitude, 
                   lng = ~ longitude,  
                   popup = ~popup_info, 
                   color = ~pop_color, 
                   radius = 3)
plot_map
                                         
```

Column {data-width=400}
-----------------------------------------------------------------------


### Number of Volcanoes and Types by Region  

```{r}
volcano <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2020/2020-05-12/volcano.csv')

#added font used in flexdashboard to the ggplot bar plot
font_add_google("Sen", family = "special")

#filter to Indonesia, select few columns for bar plot, remove plural types 
indonesia_volcanoes2 <- volcano %>% 
  filter(country == "Indonesia") %>% 
  select(subregion, primary_volcano_type) %>% 
  mutate(primary_volcano_type = str_remove(primary_volcano_type, "\\(.*\\)")) %>% 
  rename(Type = primary_volcano_type, Region = subregion)
 
 
#create plot
volcano_plot <- indonesia_volcanoes2 %>% 
  mutate(Region = Region %>% fct_infreq()) %>% 
  ggplot(aes(x = Region)) +
  geom_bar(aes(fill = Type), colour="white", alpha = 0.8) +
  dark_theme_gray(base_size = 14) +
  theme(axis.text.x = element_text(face = "bold", angle = 60, hjust = 1)) +
  labs(x = element_blank(), y = "Number of Volcanoes", fill = "Volcano Type") + 
  scale_fill_viridis_d() 
  
  
                                           
ggplotly(volcano_plot) %>% layout(legend = list("v", x = 0.8, y = 0.3))

```

Column {data-width=150}
-----------------------------------------------------------------------

### About these plots  

This is a visualization of volcanoes and their proximity residential areas and a look at 
volcanoes by region in Indonesia and the different types of volcanoes. 